POST http://localhost:9090/api/banco
Content-Type: application/json

{
    "nombre_banco":"El Pelotigue",
    "numero_cuenta":"001-002"
}

####
GET http://localhost:9090/api/banco

####
PUT http://localhost:9090/api/banco/2
Content-Type: application/json

{
    "nombre_banco":"El Pelotigue",
    "numero_cuenta":"001-002-003"
}

####
DELETE http://localhost:9090/api/banco/1